trigger: GHAS_on_Azure_DevOps_Project_Board
title: GHAS on Azure DevOps Project Board
# Works everywhere by default. Uncomment to limit it to certain surfaces.
surfaces:
 - issue

description: Creates a GHAS starter project board in Azure DevOps

# Each command has one or more steps. You can add up to 25 steps.
steps:
- type: form
  style: embedded
  body:
  - type: markdown
    attributes:
      value: |
        ## Create a Project Board for a GHAS Trial
        
        Hey there :wave:
       
        This is the form used to help create a GHAS Project Boards for Trials. Please fill in the relevant information below.
        
        Please note a repository will already need to exist within the GitHub Customers Organisation. If a repository does not exist, it will fail. 
        
        If you don't see the project board being created, check out the logs here: https://github.com/github/ghas-project-board
        
        Any questions, please feel free to reach out to a member of the GitHub Advanced Security field team :100
        
        Thanks!
        - GHAS People :+1:
        
        ----------------------

  # This displays a menu, similar to typing `@`.
  - type: menu
    id: some_options
    label: Options
    options:
      - Item 1
      - Item 2
      - Item 3
  - type: input
    attributes:
      label: Please put the repo slug. It needs to be formated org/repo. E.G githubcustomers/myrepo
      id: repo
      description: The name of the repository within the githubcustomers organisation where the project board is getting created.
      format: text
      value: githubcustomers/<REPLACE_ME>
